name: funny_macro
description: Funny Macro Controll Panel

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.3
  lottie: ^1.3.0
  flutter_countdown_timer: ^4.1.0
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  flutter_native_splash: ^2.2.3+1
flutter_native_splash:
  color: "$#00092b"
  image: assets/images/funny_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/funny_logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/funny_logo.png
    - assets/lottie/key_press.json
    - assets/lottie/war.json
    - assets/lottie/atak.json
    - assets/lottie/rpr.json
    - assets/lottie/zblock.json
    - assets/lottie/play.json

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
